# Generated by Django 4.1.3 on 2024-06-12 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0010_auto_20201211_1219"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=1)),
                (
                    "comment",
                    models.CharField(max_length=100, verbose_name="User Comment"),
                ),
                ("review_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="imgurls",
        ),
        migrations.AddField(
            model_name="booking",
            name="room_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hotel",
            name="image",
            field=models.ImageField(
                default=0, upload_to="hotel_img", verbose_name="hotelimg"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.AddField(
            model_name="review",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_reviews",
                to="book.booking",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotel_name",
                to="book.hotel",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
