# Generated by Django 4.1.3 on 2024-06-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0011_review_remove_hotel_imgurls_booking_room_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(default=0, max_length=64),
        ),
    ]
