# Generated by Django 4.1.3 on 2024-06-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0012_alter_hotel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="hotel_images/")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="book.hotel",
                    ),
                ),
            ],
        ),
    ]
