# Generated by Django 4.1.3 on 2024-06-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0013_alter_hotel_name_hotelimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel",
            old_name="rating",
            new_name="room",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="room_types",
        ),
        migrations.RemoveField(
            model_name="review",
            name="booking",
        ),
        migrations.AddField(
            model_name="booking",
            name="room_typ",
            field=models.CharField(
                choices=[("Single", "Single"), ("Dulux", "Dulux")],
                default="Single",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="hrating",
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name="hotel",
            name="room_type",
            field=models.CharField(
                choices=[("Single", "Single"), ("Dulux", "Dulux")],
                default="Single",
                max_length=64,
            ),
        ),
    ]
