# Generated by Django 4.1.3 on 2024-06-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0014_rename_rating_hotel_room_remove_hotel_room_types_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel",
            old_name="hrating",
            new_name="rating",
        ),
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
        migrations.AddField(
            model_name="review",
            name="cusrating",
            field=models.IntegerField(default=0),
        ),
    ]
